---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-gateway
  namespace: discord-gateway
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: discord-gateway
      containers:
      - image: devlaunchers/discord-gateway:sha-37e150f
        name: discord-gateway
