apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-gateway-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi