name: publish
on:
  push:
    # Only rebuild image if application code is updated, ignore changes to kubernetes
    # configs. This will prevent a commit from flux to upgrade image version from triggering
    # a build
    paths:
      - 'app.js'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devlaunchers/discord-gateway
          tag_with_ref: true
          tag_with_sha: true

